sudo: false

language: node_js

node_js:
 - "8"
 - "10"
 - "12"

cache:
  yarn: true
  directories:
    - node_modules

before_script :
 - curl -o- -L https://yarnpkg.com/install.sh | bash -s
 - export PATH=$HOME/.yarn/bin:$PATH
 - yarn install

script:
 - yarn build
 - yarn travis:lint
 - yarn travis:test

after_success:
  - cat ./test/unit/coverage/lcov.info | ./node_modules/.bin/coveralls --verbose && rm -rf ./test/unit/coverage

notifications:
  irc: "chat.freenode.net#autoNumeric"
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/d6718ebae97be830c6d5
      on_success: change  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: never     # options: [always|never|change] default: always

deploy:
  provider: npm
  email: alexandre.bonneau@linuxfr.eu
  api_key:
    secure: IZ3JO7850ODqWNudRRDvn69hEPd+z4K31A9v6O0WYKgvUwiBSJkYL+/VZhoU90cEDeEMmw1GQy9RgLdCKqTOjDtKEwsTQ1s2EllWKGSYUXbfcwnrEXjQBkRaGQOaxyUP8Oe7vJa8JTcBvcn1NDITFmQRpaThFcXSLuuEXenejuSSedWNcDzVKJi846Wu4oGOhmwd0FKBOLhfa28y6gYv4AhDVj0HVBeXlH8jWRERaco0EwwnAa3BOAaSNJCkCrrI6L22d806C4bF5q9b7nGYOoErtBjAJluxvOcAFZPg/AikWeYuvpg3psl5dVKmZuISDYTBmeZbMXbhfu8iaYaBZL6AB8HP7FRLcJETkOQoOXccmVHHDEv5kldExYtWFJmC2CYrr+Gb8Vxb2s1CBH5vblhRgTLH6pSepEca78qSyg2mZ7Lw2KciYqjnxpxp7eFbAWzSy3EuJ/RnCcHzT2PR6MbH3WO01oJcq9vL/xFip/f2eXO+7SkyCiAZdRHcMYZQtVDeZZET93QXwcPz0EFHpCSs8rjCdGATxETbmotVW9qIkYtfvwBCF1wB2UYJZ/UoQBUAIgMvgw3pxhzxAwdpUf1J2gym8g1Uluqr0agKig1YbRUX4p1i+5j4cYU5Wa11HZZkrNjAqn9CmPckIy7Z623EEvByYjCXpdB3npV0H+s=
  on:
    tags: true
    all_branches: true
    repo: autoNumeric/autoNumeric
  skip_cleanup: true
